### ISSUE TITLE
print-table breaks other ng-* directives on the td

### ISSUE THREAD

**Issue by savind** [samwiseduzer/angularPrint#10] opened 2015-11-14 00:21 UTC
After I use 'print-table', my ng-click on the td  does not work.

**Comment by samwiseduzer** [comment] 2015-11-17 23:59
could you give me an example snippet of the problem?

**Comment by samwiseduzer** [comment] 2015-12-09 00:37
Since I haven't received an example snippet and have been unable to reproduce the issue, I'm closing this issue.

**Closed as completed by samwiseduzer** 2015-12-09 00:37 UTC
